mode: pretrain

name: minimind_dataset_gpt2_61M

model:
  name: gpt2
  config:
    vocab_size: 6400
    n_layer: 8
    n_head: 8
    n_embd: 768

training:
  batch_size: 32
  seq_len: 340
  epoch_num: 2
  learning_rate: 0.0005
  warmup_steps: 100
  grad_clip: 1.0
  accumulation_steps: 8
  log_steps: 100
  seed: 42
  amp: true
  amp_dtype: bf16


checkpoint:
  save_steps: 1000
  checkpoint_dir: checkpoints/pretrain
  resume_from_checkpoint: null

data:
  data_strategy: 'padding'
  dataset_config:
    dataset_path: json
    dataset_name: ""
    data_files:
      train: /root/autodl-tmp/pretrain_t2t_mini.jsonl
    tokenizer_path: 'jingyaogong/minimind-3'
    split: 'train'
    col_name: 'text'
    add_bos_id: true
    add_eos_id: true
  dataloader_config:
    shuffle: true
    num_workers: 8
    pin_memory: true
    drop_last: false
    persistent_workers: false
    seed: 42

eval:
  steps: 1000
  dataset_path: json
  dataset_name: ""
  data_files:
    train: /root/autodl-tmp/pretrain_t2t_eval_unseen_1024.jsonl
  split: train
  text_column: text
  tokenizer_path: jingyaogong/minimind-3
  max_samples: 1024
  batch_size: 16
  add_bos_id: true
  add_eos_id: true
  checkpoint_step: null

optimizer:
  name: adamw
  weight_decay: 0.0
  betas: [0.9, 0.999]
  eps: 1.0e-8

swanlab:
  enabled: true
  project: llm-pretrain
  experiment_name: minimind_dataset_gpt2_61M
  tags: []
