experiment:
  mode: pretrain
  name: minimind_dataset_gpt2_61M_ds_zero2_ckpt_1
  swanlab:
    enabled: true
    project: llm-pretrain
    tags: [deepspeed, zero0]

model:
  name: gpt2
  config:
    vocab_size: 6400
    n_layer: 8
    n_head: 8
    n_embd: 768

train:
  batch_size: 64
  seq_len: 340
  epoch_num: 2
  log_steps: 100
  seed: 42
  backend: deepspeed
  deepspeed_config: /root/llm_from_zero_to_one/configs/deepspeed_zero0_autodl_pretrain_minimind.json

checkpoint:
  save_step: 50
  save_checkpoint_dir: /root/autodl-tmp/checkpoint
  resume_checkpoint_dir: /root/autodl-tmp/checkpoint/minimind_dataset_gpt2_61M_ds_zero2_ckpt_1
  resume_tag: global_step50

data:
  train:
    data_strategy: padding
    dataset_config:
      dataset_path: json
      dataset_name: ""
      data_files:
        train: /root/autodl-tmp/pretrain.jsonl
      tokenizer_path: jingyaogong/minimind-3
      split: train
      col_name: text
      add_bos_id: true
      add_eos_id: true
    dataloader_config:
      shuffle: true
      num_workers: 8
      pin_memory: true
      drop_last: false
      persistent_workers: false
      seed: 42
