mode: eval

name: minimind_gpt2_padding_example

model:
  name: gpt2
  config:
    vocab_size: 6400
    n_layer: 8
    n_head: 8
    n_embd: 768

training:
  seq_len: 340

checkpoint:
  checkpoint_dir: checkpoints/pretrain

eval:
  dataset_path: wikitext
  dataset_name: wikitext-2-raw-v1
  split: test
  text_column: text
  tokenizer_path: jingyaogong/minimind-3
  max_samples: 256
  batch_size: 8
  add_bos_id: false
  add_eos_id: true
  checkpoint_step: 4960
