mode: pretrain

model:
  name: gpt2
  config:
    block_size: 1024
    vocab_size: 50257
    n_layer: 12
    n_head: 12
    n_embd: 768

training:
  batch_size: 16
  seq_len: 1024
  epoch_num: 1
  learning_rate: 0.0003
  warmup_steps: 10
  grad_clip: 1.0
  accumulation_steps: 4
  log_steps: 10

checkpoint:
  save_steps: 1000
  checkpoint_dir: checkpoints/pretrain
  resume_from_checkpoint: null

data:
  data_strategy: 'padding'
  data_path: 'roneneldan/TinyStories'
  dataset_config:
    max_seq: 1024
    split: 'train'
    col_name: 'text'
    add_bos_id: false
    add_eos_id: true

device: cpu

inference:
  steps: 500
  tokens: 100
  topk: 100
  temperature: 1.0
  prompt: The meaning of life is
